# Generated by Django 4.1.3 on 2022-12-03 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0002_curriculums'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstructionalPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(default='NA', max_length=2)),
                ('course', models.ManyToManyField(to='registrations.curriculums')),
                ('student', models.ManyToManyField(to='registrations.students')),
            ],
        ),
    ]
