# Generated by Django 4.1.3 on 2022-12-03 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0003_instructionalplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='curriculums',
            name='grade',
            field=models.CharField(default='NA', max_length=2),
        ),
        migrations.AddField(
            model_name='curriculums',
            name='student',
            field=models.ManyToManyField(to='registrations.students'),
        ),
        migrations.DeleteModel(
            name='InstructionalPlan',
        ),
    ]
