# Generated by Django 4.1.3 on 2022-12-03 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0004_curriculums_grade_curriculums_student_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curriculums',
            name='grade',
        ),
        migrations.CreateModel(
            name='InstructionalPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(default='NA', max_length=2)),
                ('curriculum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registrations.curriculums')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registrations.students')),
            ],
        ),
    ]
