# Generated by Django 4.1.3 on 2022-12-07 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0006_alter_curriculums_department_alter_students_advisor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curriculums',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='registrations.departments'),
        ),
        migrations.AlterField(
            model_name='students',
            name='advisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='registrations.academicstaff'),
        ),
        migrations.AlterField(
            model_name='students',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='registrations.departments'),
        ),
        migrations.AlterField(
            model_name='students',
            name='faculty',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='registrations.faculties'),
        ),
    ]
